/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.binto.YYSchedule.common.rpc.domain.job;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * job distribution mode enumeration
 */
public enum JobDistributionMode implements org.apache.thrift.TEnum {
  SERIAL(0),
  PARALLEL(1);

  private final int value;

  private JobDistributionMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobDistributionMode findByValue(int value) { 
    switch (value) {
      case 0:
        return SERIAL;
      case 1:
        return PARALLEL;
      default:
        return null;
    }
  }
}
