/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.binto.YYSchedule.common.rpc.domain.job;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * job resource requirement
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-06-11")
public class JobResourceRequirement implements org.apache.thrift.TBase<JobResourceRequirement, JobResourceRequirement._Fields>, java.io.Serializable, Cloneable, Comparable<JobResourceRequirement> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JobResourceRequirement");

  private static final org.apache.thrift.protocol.TField TASK_PHASE_FIELD_DESC = new org.apache.thrift.protocol.TField("taskPhase", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PROGRAM_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("programId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField EXECUTOR_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("executorId", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new JobResourceRequirementStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new JobResourceRequirementTupleSchemeFactory();

  /**
   * 
   * @see com.binto.YYSchedule.common.rpc.domain.task.TaskPhase
   */
  public com.binto.YYSchedule.common.rpc.domain.task.TaskPhase taskPhase; // required
  public long programId; // optional
  public java.lang.String executorId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see com.binto.YYSchedule.common.rpc.domain.task.TaskPhase
     */
    TASK_PHASE((short)1, "taskPhase"),
    PROGRAM_ID((short)2, "programId"),
    EXECUTOR_ID((short)3, "executorId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TASK_PHASE
          return TASK_PHASE;
        case 2: // PROGRAM_ID
          return PROGRAM_ID;
        case 3: // EXECUTOR_ID
          return EXECUTOR_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROGRAMID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.PROGRAM_ID,_Fields.EXECUTOR_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TASK_PHASE, new org.apache.thrift.meta_data.FieldMetaData("taskPhase", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.binto.YYSchedule.common.rpc.domain.task.TaskPhase.class)));
    tmpMap.put(_Fields.PROGRAM_ID, new org.apache.thrift.meta_data.FieldMetaData("programId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.EXECUTOR_ID, new org.apache.thrift.meta_data.FieldMetaData("executorId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JobResourceRequirement.class, metaDataMap);
  }

  public JobResourceRequirement() {
  }

  public JobResourceRequirement(
    com.binto.YYSchedule.common.rpc.domain.task.TaskPhase taskPhase)
  {
    this();
    this.taskPhase = taskPhase;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JobResourceRequirement(JobResourceRequirement other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTaskPhase()) {
      this.taskPhase = other.taskPhase;
    }
    this.programId = other.programId;
    if (other.isSetExecutorId()) {
      this.executorId = other.executorId;
    }
  }

  public JobResourceRequirement deepCopy() {
    return new JobResourceRequirement(this);
  }

  @Override
  public void clear() {
    this.taskPhase = null;
    setProgramIdIsSet(false);
    this.programId = 0;
    this.executorId = null;
  }

  /**
   * 
   * @see com.binto.YYSchedule.common.rpc.domain.task.TaskPhase
   */
  public com.binto.YYSchedule.common.rpc.domain.task.TaskPhase getTaskPhase() {
    return this.taskPhase;
  }

  /**
   * 
   * @see com.binto.YYSchedule.common.rpc.domain.task.TaskPhase
   */
  public JobResourceRequirement setTaskPhase(com.binto.YYSchedule.common.rpc.domain.task.TaskPhase taskPhase) {
    this.taskPhase = taskPhase;
    return this;
  }

  public void unsetTaskPhase() {
    this.taskPhase = null;
  }

  /** Returns true if field taskPhase is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskPhase() {
    return this.taskPhase != null;
  }

  public void setTaskPhaseIsSet(boolean value) {
    if (!value) {
      this.taskPhase = null;
    }
  }

  public long getProgramId() {
    return this.programId;
  }

  public JobResourceRequirement setProgramId(long programId) {
    this.programId = programId;
    setProgramIdIsSet(true);
    return this;
  }

  public void unsetProgramId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PROGRAMID_ISSET_ID);
  }

  /** Returns true if field programId is set (has been assigned a value) and false otherwise */
  public boolean isSetProgramId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PROGRAMID_ISSET_ID);
  }

  public void setProgramIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PROGRAMID_ISSET_ID, value);
  }

  public java.lang.String getExecutorId() {
    return this.executorId;
  }

  public JobResourceRequirement setExecutorId(java.lang.String executorId) {
    this.executorId = executorId;
    return this;
  }

  public void unsetExecutorId() {
    this.executorId = null;
  }

  /** Returns true if field executorId is set (has been assigned a value) and false otherwise */
  public boolean isSetExecutorId() {
    return this.executorId != null;
  }

  public void setExecutorIdIsSet(boolean value) {
    if (!value) {
      this.executorId = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case TASK_PHASE:
      if (value == null) {
        unsetTaskPhase();
      } else {
        setTaskPhase((com.binto.YYSchedule.common.rpc.domain.task.TaskPhase)value);
      }
      break;

    case PROGRAM_ID:
      if (value == null) {
        unsetProgramId();
      } else {
        setProgramId((java.lang.Long)value);
      }
      break;

    case EXECUTOR_ID:
      if (value == null) {
        unsetExecutorId();
      } else {
        setExecutorId((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TASK_PHASE:
      return getTaskPhase();

    case PROGRAM_ID:
      return getProgramId();

    case EXECUTOR_ID:
      return getExecutorId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TASK_PHASE:
      return isSetTaskPhase();
    case PROGRAM_ID:
      return isSetProgramId();
    case EXECUTOR_ID:
      return isSetExecutorId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof JobResourceRequirement)
      return this.equals((JobResourceRequirement)that);
    return false;
  }

  public boolean equals(JobResourceRequirement that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_taskPhase = true && this.isSetTaskPhase();
    boolean that_present_taskPhase = true && that.isSetTaskPhase();
    if (this_present_taskPhase || that_present_taskPhase) {
      if (!(this_present_taskPhase && that_present_taskPhase))
        return false;
      if (!this.taskPhase.equals(that.taskPhase))
        return false;
    }

    boolean this_present_programId = true && this.isSetProgramId();
    boolean that_present_programId = true && that.isSetProgramId();
    if (this_present_programId || that_present_programId) {
      if (!(this_present_programId && that_present_programId))
        return false;
      if (this.programId != that.programId)
        return false;
    }

    boolean this_present_executorId = true && this.isSetExecutorId();
    boolean that_present_executorId = true && that.isSetExecutorId();
    if (this_present_executorId || that_present_executorId) {
      if (!(this_present_executorId && that_present_executorId))
        return false;
      if (!this.executorId.equals(that.executorId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTaskPhase()) ? 131071 : 524287);
    if (isSetTaskPhase())
      hashCode = hashCode * 8191 + taskPhase.getValue();

    hashCode = hashCode * 8191 + ((isSetProgramId()) ? 131071 : 524287);
    if (isSetProgramId())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(programId);

    hashCode = hashCode * 8191 + ((isSetExecutorId()) ? 131071 : 524287);
    if (isSetExecutorId())
      hashCode = hashCode * 8191 + executorId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(JobResourceRequirement other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTaskPhase()).compareTo(other.isSetTaskPhase());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskPhase()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskPhase, other.taskPhase);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProgramId()).compareTo(other.isSetProgramId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProgramId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.programId, other.programId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetExecutorId()).compareTo(other.isSetExecutorId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExecutorId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.executorId, other.executorId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("JobResourceRequirement(");
    boolean first = true;

    sb.append("taskPhase:");
    if (this.taskPhase == null) {
      sb.append("null");
    } else {
      sb.append(this.taskPhase);
    }
    first = false;
    if (isSetProgramId()) {
      if (!first) sb.append(", ");
      sb.append("programId:");
      sb.append(this.programId);
      first = false;
    }
    if (isSetExecutorId()) {
      if (!first) sb.append(", ");
      sb.append("executorId:");
      if (this.executorId == null) {
        sb.append("null");
      } else {
        sb.append(this.executorId);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (taskPhase == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskPhase' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class JobResourceRequirementStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JobResourceRequirementStandardScheme getScheme() {
      return new JobResourceRequirementStandardScheme();
    }
  }

  private static class JobResourceRequirementStandardScheme extends org.apache.thrift.scheme.StandardScheme<JobResourceRequirement> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, JobResourceRequirement struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TASK_PHASE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.taskPhase = com.binto.YYSchedule.common.rpc.domain.task.TaskPhase.findByValue(iprot.readI32());
              struct.setTaskPhaseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROGRAM_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.programId = iprot.readI64();
              struct.setProgramIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXECUTOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.executorId = iprot.readString();
              struct.setExecutorIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, JobResourceRequirement struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.taskPhase != null) {
        oprot.writeFieldBegin(TASK_PHASE_FIELD_DESC);
        oprot.writeI32(struct.taskPhase.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.isSetProgramId()) {
        oprot.writeFieldBegin(PROGRAM_ID_FIELD_DESC);
        oprot.writeI64(struct.programId);
        oprot.writeFieldEnd();
      }
      if (struct.executorId != null) {
        if (struct.isSetExecutorId()) {
          oprot.writeFieldBegin(EXECUTOR_ID_FIELD_DESC);
          oprot.writeString(struct.executorId);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class JobResourceRequirementTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JobResourceRequirementTupleScheme getScheme() {
      return new JobResourceRequirementTupleScheme();
    }
  }

  private static class JobResourceRequirementTupleScheme extends org.apache.thrift.scheme.TupleScheme<JobResourceRequirement> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, JobResourceRequirement struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.taskPhase.getValue());
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetProgramId()) {
        optionals.set(0);
      }
      if (struct.isSetExecutorId()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetProgramId()) {
        oprot.writeI64(struct.programId);
      }
      if (struct.isSetExecutorId()) {
        oprot.writeString(struct.executorId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, JobResourceRequirement struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.taskPhase = com.binto.YYSchedule.common.rpc.domain.task.TaskPhase.findByValue(iprot.readI32());
      struct.setTaskPhaseIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.programId = iprot.readI64();
        struct.setProgramIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.executorId = iprot.readString();
        struct.setExecutorIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

