#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport


class Iface(object):
    """
    nodemanager作为服务端，等待引擎通过rpc调用
    """
    def transferResult(self, taskId, file, result, logger, isSuccess):
        """
        receive result
        @param	taskId
        @param	fileName
        @param	result
        @param	logger
        @return	succeed or not

        Parameters:
         - taskId
         - file
         - result
         - logger
         - isSuccess
        """
        pass

    def submitExecutionLogger(self, taskId, file, content):
        """
        提交引擎执行过程中产生的日志信息
        @param	taskId
        @param	content
        @return	succeed or not

        Parameters:
         - taskId
         - file
         - content
        """
        pass


class Client(Iface):
    """
    nodemanager作为服务端，等待引擎通过rpc调用
    """
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def transferResult(self, taskId, file, result, logger, isSuccess):
        """
        receive result
        @param	taskId
        @param	fileName
        @param	result
        @param	logger
        @return	succeed or not

        Parameters:
         - taskId
         - file
         - result
         - logger
         - isSuccess
        """
        self.send_transferResult(taskId, file, result, logger, isSuccess)
        return self.recv_transferResult()

    def send_transferResult(self, taskId, file, result, logger, isSuccess):
        self._oprot.writeMessageBegin('transferResult', TMessageType.CALL, self._seqid)
        args = transferResult_args()
        args.taskId = taskId
        args.file = file
        args.result = result
        args.logger = logger
        args.isSuccess = isSuccess
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_transferResult(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = transferResult_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.ire is not None:
            raise result.ire
        if result.ue is not None:
            raise result.ue
        if result.te is not None:
            raise result.te
        raise TApplicationException(TApplicationException.MISSING_RESULT, "transferResult failed: unknown result")

    def submitExecutionLogger(self, taskId, file, content):
        """
        提交引擎执行过程中产生的日志信息
        @param	taskId
        @param	content
        @return	succeed or not

        Parameters:
         - taskId
         - file
         - content
        """
        self.send_submitExecutionLogger(taskId, file, content)
        return self.recv_submitExecutionLogger()

    def send_submitExecutionLogger(self, taskId, file, content):
        self._oprot.writeMessageBegin('submitExecutionLogger', TMessageType.CALL, self._seqid)
        args = submitExecutionLogger_args()
        args.taskId = taskId
        args.file = file
        args.content = content
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_submitExecutionLogger(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = submitExecutionLogger_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.ire is not None:
            raise result.ire
        if result.ue is not None:
            raise result.ue
        if result.te is not None:
            raise result.te
        raise TApplicationException(TApplicationException.MISSING_RESULT, "submitExecutionLogger failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["transferResult"] = Processor.process_transferResult
        self._processMap["submitExecutionLogger"] = Processor.process_submitExecutionLogger

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_transferResult(self, seqid, iprot, oprot):
        args = transferResult_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = transferResult_result()
        try:
            result.success = self._handler.transferResult(args.taskId, args.file, args.result, args.logger, args.isSuccess)
            msg_type = TMessageType.REPLY
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except rpc.exception.ttypes.InvalidRequestException as ire:
            msg_type = TMessageType.REPLY
            result.ire = ire
        except rpc.exception.ttypes.UnavailableException as ue:
            msg_type = TMessageType.REPLY
            result.ue = ue
        except rpc.exception.ttypes.TimeoutException as te:
            msg_type = TMessageType.REPLY
            result.te = te
        except Exception as ex:
            msg_type = TMessageType.EXCEPTION
            logging.exception(ex)
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("transferResult", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_submitExecutionLogger(self, seqid, iprot, oprot):
        args = submitExecutionLogger_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = submitExecutionLogger_result()
        try:
            result.success = self._handler.submitExecutionLogger(args.taskId, args.file, args.content)
            msg_type = TMessageType.REPLY
        except (TTransport.TTransportException, KeyboardInterrupt, SystemExit):
            raise
        except rpc.exception.ttypes.InvalidRequestException as ire:
            msg_type = TMessageType.REPLY
            result.ire = ire
        except rpc.exception.ttypes.UnavailableException as ue:
            msg_type = TMessageType.REPLY
            result.ue = ue
        except rpc.exception.ttypes.TimeoutException as te:
            msg_type = TMessageType.REPLY
            result.te = te
        except Exception as ex:
            msg_type = TMessageType.EXCEPTION
            logging.exception(ex)
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("submitExecutionLogger", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class transferResult_args(object):
    """
    Attributes:
     - taskId
     - file
     - result
     - logger
     - isSuccess
    """

    thrift_spec = (
        None,  # 0
        (1, TType.I64, 'taskId', None, None, ),  # 1
        (2, TType.STRING, 'file', 'UTF8', None, ),  # 2
        (3, TType.STRING, 'result', 'UTF8', None, ),  # 3
        (4, TType.STRING, 'logger', 'UTF8', None, ),  # 4
        (5, TType.BOOL, 'isSuccess', None, None, ),  # 5
    )

    def __init__(self, taskId=None, file=None, result=None, logger=None, isSuccess=None,):
        self.taskId = taskId
        self.file = file
        self.result = result
        self.logger = logger
        self.isSuccess = isSuccess

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.taskId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.file = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.result = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.logger = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.BOOL:
                    self.isSuccess = iprot.readBool()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('transferResult_args')
        if self.taskId is not None:
            oprot.writeFieldBegin('taskId', TType.I64, 1)
            oprot.writeI64(self.taskId)
            oprot.writeFieldEnd()
        if self.file is not None:
            oprot.writeFieldBegin('file', TType.STRING, 2)
            oprot.writeString(self.file.encode('utf-8') if sys.version_info[0] == 2 else self.file)
            oprot.writeFieldEnd()
        if self.result is not None:
            oprot.writeFieldBegin('result', TType.STRING, 3)
            oprot.writeString(self.result.encode('utf-8') if sys.version_info[0] == 2 else self.result)
            oprot.writeFieldEnd()
        if self.logger is not None:
            oprot.writeFieldBegin('logger', TType.STRING, 4)
            oprot.writeString(self.logger.encode('utf-8') if sys.version_info[0] == 2 else self.logger)
            oprot.writeFieldEnd()
        if self.isSuccess is not None:
            oprot.writeFieldBegin('isSuccess', TType.BOOL, 5)
            oprot.writeBool(self.isSuccess)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.taskId is None:
            raise TProtocolException(message='Required field taskId is unset!')
        if self.file is None:
            raise TProtocolException(message='Required field file is unset!')
        if self.logger is None:
            raise TProtocolException(message='Required field logger is unset!')
        if self.isSuccess is None:
            raise TProtocolException(message='Required field isSuccess is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class transferResult_result(object):
    """
    Attributes:
     - success
     - ire
     - ue
     - te
    """

    thrift_spec = (
        (0, TType.I32, 'success', None, None, ),  # 0
        (1, TType.STRUCT, 'ire', (rpc.exception.ttypes.InvalidRequestException, rpc.exception.ttypes.InvalidRequestException.thrift_spec), None, ),  # 1
        (2, TType.STRUCT, 'ue', (rpc.exception.ttypes.UnavailableException, rpc.exception.ttypes.UnavailableException.thrift_spec), None, ),  # 2
        (3, TType.STRUCT, 'te', (rpc.exception.ttypes.TimeoutException, rpc.exception.ttypes.TimeoutException.thrift_spec), None, ),  # 3
    )

    def __init__(self, success=None, ire=None, ue=None, te=None,):
        self.success = success
        self.ire = ire
        self.ue = ue
        self.te = te

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.I32:
                    self.success = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.ire = rpc.exception.ttypes.InvalidRequestException()
                    self.ire.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.ue = rpc.exception.ttypes.UnavailableException()
                    self.ue.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.te = rpc.exception.ttypes.TimeoutException()
                    self.te.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('transferResult_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.I32, 0)
            oprot.writeI32(self.success)
            oprot.writeFieldEnd()
        if self.ire is not None:
            oprot.writeFieldBegin('ire', TType.STRUCT, 1)
            self.ire.write(oprot)
            oprot.writeFieldEnd()
        if self.ue is not None:
            oprot.writeFieldBegin('ue', TType.STRUCT, 2)
            self.ue.write(oprot)
            oprot.writeFieldEnd()
        if self.te is not None:
            oprot.writeFieldBegin('te', TType.STRUCT, 3)
            self.te.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class submitExecutionLogger_args(object):
    """
    Attributes:
     - taskId
     - file
     - content
    """

    thrift_spec = (
        None,  # 0
        (1, TType.I64, 'taskId', None, None, ),  # 1
        (2, TType.STRING, 'file', 'UTF8', None, ),  # 2
        (3, TType.STRING, 'content', 'UTF8', None, ),  # 3
    )

    def __init__(self, taskId=None, file=None, content=None,):
        self.taskId = taskId
        self.file = file
        self.content = content

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.taskId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.file = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.content = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('submitExecutionLogger_args')
        if self.taskId is not None:
            oprot.writeFieldBegin('taskId', TType.I64, 1)
            oprot.writeI64(self.taskId)
            oprot.writeFieldEnd()
        if self.file is not None:
            oprot.writeFieldBegin('file', TType.STRING, 2)
            oprot.writeString(self.file.encode('utf-8') if sys.version_info[0] == 2 else self.file)
            oprot.writeFieldEnd()
        if self.content is not None:
            oprot.writeFieldBegin('content', TType.STRING, 3)
            oprot.writeString(self.content.encode('utf-8') if sys.version_info[0] == 2 else self.content)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.taskId is None:
            raise TProtocolException(message='Required field taskId is unset!')
        if self.file is None:
            raise TProtocolException(message='Required field file is unset!')
        if self.content is None:
            raise TProtocolException(message='Required field content is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class submitExecutionLogger_result(object):
    """
    Attributes:
     - success
     - ire
     - ue
     - te
    """

    thrift_spec = (
        (0, TType.I32, 'success', None, None, ),  # 0
        (1, TType.STRUCT, 'ire', (rpc.exception.ttypes.InvalidRequestException, rpc.exception.ttypes.InvalidRequestException.thrift_spec), None, ),  # 1
        (2, TType.STRUCT, 'ue', (rpc.exception.ttypes.UnavailableException, rpc.exception.ttypes.UnavailableException.thrift_spec), None, ),  # 2
        (3, TType.STRUCT, 'te', (rpc.exception.ttypes.TimeoutException, rpc.exception.ttypes.TimeoutException.thrift_spec), None, ),  # 3
    )

    def __init__(self, success=None, ire=None, ue=None, te=None,):
        self.success = success
        self.ire = ire
        self.ue = ue
        self.te = te

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.I32:
                    self.success = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.ire = rpc.exception.ttypes.InvalidRequestException()
                    self.ire.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.ue = rpc.exception.ttypes.UnavailableException()
                    self.ue.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.te = rpc.exception.ttypes.TimeoutException()
                    self.te.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('submitExecutionLogger_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.I32, 0)
            oprot.writeI32(self.success)
            oprot.writeFieldEnd()
        if self.ire is not None:
            oprot.writeFieldBegin('ire', TType.STRUCT, 1)
            self.ire.write(oprot)
            oprot.writeFieldEnd()
        if self.ue is not None:
            oprot.writeFieldBegin('ue', TType.STRUCT, 2)
            self.ue.write(oprot)
            oprot.writeFieldEnd()
        if self.te is not None:
            oprot.writeFieldBegin('te', TType.STRUCT, 3)
            self.te.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
