/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.binto.YYSchedule.common.rpc.domain.node;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ClusterType implements org.apache.thrift.TEnum {
  DEDICATED(0),
  GENERAL(1);

  private final int value;

  private ClusterType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ClusterType findByValue(int value) { 
    switch (value) {
      case 0:
        return DEDICATED;
      case 1:
        return GENERAL;
      default:
        return null;
    }
  }
}
